# Generated by Django 5.0.6 on 2024-05-21 19:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_public', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('years', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
