# Generated by Django 5.0.6 on 2024-05-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertasks',
            name='nickname',
        ),
        migrations.AddField(
            model_name='usertasks',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.users'),
        ),
    ]
