# Generated by Django 5.0.6 on 2024-05-28 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usertasks_nickname_usertasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.users'),
        ),
    ]
