# Generated by Django 5.0.6 on 2024-05-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usertasks_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertasks',
            old_name='task',
            new_name='title',
        ),
    ]
