# Generated by Django 5.0.6 on 2024-05-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usertasks_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTasks',
        ),
    ]
