# Generated by Django 5.0.6 on 2024-05-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usertasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='users.users'),
        ),
    ]
