# Generated by Django 5.0.6 on 2024-05-29 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_users_id_alter_usertasks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to='users.users'),
        ),
    ]
