# Generated by Django 5.0.6 on 2024-05-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_usertasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
