# Generated by Django 5.0.6 on 2024-05-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('years', models.IntegerField()),
            ],
        ),
    ]
