# Generated by Django 5.0.6 on 2024-05-17 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0002_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
